Scan mode=rapid on pull requests
akram8008/jenkins-library pull request #1
Opened 2022-12-14 14:49 UTC by akram8008

# Changes

- [ ] Tests
- [ ] Documentation

2022-12-15 15:56 UTC, andrew-kireev requested changes

2022-12-15 15:56 UTC, andrew-kireev commented on pkg/reporting/pullRequestReport.go
> +func (a Files) Less(i, j int) bool { return a[i].Name() < a[j].Name() }
I think is is better to just find last created file because it has less complexity than sorting files and we only need the last created directory. The same way it was done in repository which creates pull requests comments using GitHub actions.

```suggestion
func findLastCreatedDir(directories []os.DirEntry) os.DirEntry {
	lastCreatedDir := directories[0]
	for _, dir := range directories {
		if dir.Name() > lastCreatedDir.Name() {
			lastCreatedDir = dir
		}
	}

	return lastCreatedDir
}
```

2022-12-15 15:56 UTC, andrew-kireev commented on pkg/reporting/pullRequestReport.go
> +	filePath = filePath + "/" + allFiles[0].Name() + "/scan"
```suggestion
	lastDir := findLastCreatedDir(allFiles)

	removeDir := filePath + "/" + lastDir.Name()
	filePath = filePath + "/" + lastDir.Name() + "/scan"
```

2022-12-15 16:05 UTC, andrew-kireev commented on pkg/reporting/pullRequestReport.go
> +		log.Println("couldn't remove report file")
It seems to me that is would be better to use package `github.com/SAP/jenkins-library/pkg/log` to write logs because it is used across project and it makes possible to specify log level.
```suggestion
		log.Entry().Warn("couldn't remove report file")
```

2023-01-13 14:42 UTC, andrew-kireev approved these changes
From my perspective, everything is fine

2023-02-15 21:38 UTC, akram8008 commented
### Description
  1. About feature
     1. [Documentation url (not final version)](https://github.com/akram8008/jenkins-library/blob/feature/detectExecuation_PR_scans/documentation/docs/steps/detectExecuteScan.md)
  2. In part of the code
     1. A new GetProvider() method has been added to the cmd/detectExecuteScan.go file
     2. Used the GetProvider() method to detect the pull request
     3. When a pull request is detected, additional parameters will be added:
          1. "--detect.blackduck.scan.mode='RAPID'" - to change scan mode from "FULL" to "RAPID"
          2. "--detect.blackduck.rapid.compare.mode='BOM_COMPARE_STRICT'" - for package list comparison method
          3. "--detect.cleanup=false" - in order not to clear the scan results file
          4. "--detect.output.path='report'" - the path to save the results file
     4. Added the ability to read from a result file and send it to the pull request comment in markdown format

2023-04-11 00:05 UTC, closed without merging